userConfig:
  server: 1
  name: 测试工具
  account: testaccount
  password: testpassword
deduceConfig:
  type: 内功
  entrys:
    - entry: 臂力
      level: 0
      prior: false
    - entry: 攻击百分比
      level: 0
      prior: false
    - entry: 绝招冷却时间百分比
      level: 230
      prior: true
    - entry: 最终伤害
      level: 0
      prior: false
    - entry: 剑心
      level: 160
      prior: true
accessories:
  food: true
  fy: true
  xlu: true
autoReLogin: true
checkStatusOnLevelUp: false
